### ISSUE TITLE
Cannot Access AdvancedCompany Perks Menu

### ISSUE THREAD

**Issue by nephatrine** [RegisSlim/ImmersiveCompany#1]
When I try to access the Perks menu via the `perks` command, it just tries to by a personal radar. Would love a config option to disable the personal radar.

**Comment by nephatrine** [comment]
Nevermind. The thunderstore documentation on AdvanceCompany is out of date and it has a separate terminal now. Wouldn't mind still having config options, but I'll close this since it's irrelevant.

**Comment by RegisSlim** [comment]
Config added in version 0.3.0
